// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using part4.Contexts;
using System;

namespace part4.Migrations.ComputerCartItems
{
    [DbContext(typeof(ComputerCartItemsContext))]
    [Migration("20180123042413_ComputerCartItemsContextTable")]
    partial class ComputerCartItemsContextTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("part4.Models.CartComputer", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CPUid");

                    b.Property<Guid>("Displayid");

                    b.Property<Guid>("HDid");

                    b.Property<Guid>("OSid");

                    b.Property<Guid>("RAMid");

                    b.Property<Guid>("SoundCardid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(700);

                    b.Property<string>("image")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("price");

                    b.HasKey("id");

                    b.ToTable("cartcomps");
                });
#pragma warning restore 612, 618
        }
    }
}
